<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="SMBLibrary" Version="1.5.7.1" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Duetto.Tests" />
  </ItemGroup>

</Project>
